### ISSUE TITLE
Missing link to reference.html on https://libexpat.github.io/

### ISSUE THREAD

**Issue by pointsman** [libexpat/libexpat.github.io#18]
The subject says it all - do I just miss it or is reference.html not linked on https://libexpat.github.io/ ?

It seems natural to expect the API documentation somewhere on that page, say on https://libexpat.github.io/doc/, no?

I stumbled over this while on search of a link to the API reference documentation to be used in another conversation.

**Comment by hartwork** [comment]
> I'm aware that the file is in the repository, but linking to the HTML source isn't so sexy (without the HTML source rendered by a browser).

I agree, yes.

> So I would be thankful if this could be eventually resolved, if your time and other tasks allow.

Cool, thanks.

@pointsman note that I have moved the issue over to the website repository at https://github.com/libexpat/libexpat.github.io as issue #18 now. In case you wonder or don't find it at its original place. (The original URL probably forwards, but still.)

**Comment by hartwork** [comment]
Closing as fixed, now online at https://libexpat.github.io/doc/api/latest/ .

**Comment by pointsman** [comment]
Am 18.02.22 um 01:53 schrieb Sebastian Pipping:
> Closing as fixed, now online at https://libexpat.github.io/doc/api/latest/ .

Works for me. Txt!
